= At README
:toc: left
:experimental:

++++
<script src="https://darshandsoni.com/asciidoctor-skins/switcher.js" type="text/javascript"></script>
++++

For both at and batch, commands are read from standard input or the file specified with the -f option and executed. The working directory, the environment (except for the variables BASH_VERSINFO, DISPLAY, EUID, GROUPS, SHELLOPTS, TERM, UID, and _) and the umask are retained from the time of invocation.

As at is currently implemented as a setuid program, other environment variables (e.g., LD_LIBRARY_PATH or LD_PRELOAD) are also not exported. This may change in the future. As a workaround, set these variables explicitly in your job.

An at or batch command run from a su shell will retain the current userid. The user will be mailed standard error and standard output from his commands, if any. Mail will be sent using the command /usr/sbin/sendmail. If at is executed from a su shell, the owner of the login shell will receive the mail.

The superuser may always use these commands. For other users, permission to use at is determined by the files /etc/at.allow and /etc/at.deny. See at.allow for details.

.At.sh
[source,bash,linenums]
----
# Schedule job
at -f <script> <time>

at now + 1 minute
at 4pm + 3 (days|weeks|months|years)
at 10:00 AM July 25
at 10:00 AM 6/22/2015
at midnight

#To exit the at prompt we should press the CTRL+d key combination.

at now + 1 minute -f script.sh

# or

echo "sh backup.sh" | at 9:00 AM



# List jobs
atq
# 16      Wed Jul 11 02:00:00 2007 a ian
# 17      Sat Jul 14 02:00:00 2007 a ian
# 14      Sun Jul  8 22:00:00 2007 a ian
# 15      Tue Jul 10 02:00:00 2007 a ian
# Remove jobs
atrm 16 14 15
----

== Options


== References

* https://www.ibm.com/developerworks/library/l-job-scheduling/index.html
* https://www.ibm.com/developerworks/library/l-job-scheduling/index.html
* https://linuxconfig.org/how-to-schedule-tasks-using-at-command-on-linux
* https://www.computerhope.com/unix/uat.htm
