#!/usr/bin/env python3

"""A simple python script template.


Sources: 
https://docs.python.org/3/library/argparse.html
"""

import os
import sys
import argparse

def main(arguments):

    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument('--verbose', '-v', help="Verbosity. Could be multiple to increase level.",
                        action='count', default=0)
    parser.add_argument('-i','--infile', help="Input file", type=str)
    parser.add_argument('-o', '--outfile', help="Output file",
                        default=sys.stdout, type=str)


    args = parser.parse_args(arguments)

    print(args)

if __name__ == '__main__':


    sys.exit(main(sys.argv[1:]))


