#!/bin/csh
# -*- shell-script -*-
########################################################################
#  This is the system wide source file for setting up
#  modules:
#
########################################################################

set MY_NAME="/ascldap/users/fsabado/lmod/lmod/init/cshrc"



if ( ! $?MODULEPATH_ROOT ) then
    if ( $?USER) then
        setenv USER $LOGNAME
    endif

    set UNAME = `uname`
    setenv LMOD_sys             $UNAME
    setenv MODULEPATH_ROOT      "/ascldap/users/fsabado/modulefiles"
    set MODULEPATH_INIT = "/ascldap/users/fsabado/lmod/lmod/init/.modulespath"
    if ( -f $MODULEPATH_INIT ) then
       	foreach str (`cat $MODULEPATH_INIT | sed 's/#.*$//'`)	# Allow end-of-line comments.
	   foreach dir ( $str )
              if ( -d $dir ) then
                 setenv MODULEPATH `/ascldap/users/fsabado/lmod/lmod/libexec/addto --append MODULEPATH $dir`
              endif
           end
	end
    else
       setenv MODULEPATH `/ascldap/users/fsabado/lmod/lmod/libexec/addto --append MODULEPATH $MODULEPATH_ROOT/$LMOD_sys $MODULEPATH_ROOT/Core`
       setenv MODULEPATH `/ascldap/users/fsabado/lmod/lmod/libexec/addto --append MODULEPATH /ascldap/users/fsabado/lmod/lmod/modulefiles/Core`
    endif

    setenv BASH_ENV             "/ascldap/users/fsabado/lmod/lmod/init/bash"

    #
    # If MANPATH is empty, Lmod is adding a trailing ":" so that
    # the system MANPATH will be found
    if ( ! $?MANPATH ) then
      setenv MANPATH :
    endif
    setenv MANPATH `/ascldap/users/fsabado/lmod/lmod/libexec/addto MANPATH /ascldap/users/fsabado/lmod/lmod/share/man`

endif

if ( -f  /ascldap/users/fsabado/lmod/lmod/init/csh  ) then
  source /ascldap/users/fsabado/lmod/lmod/init/csh
endif

# Local Variables:
# mode: shell-script
# indent-tabs-mode: nil
# End:

